services:
  postgres-demo-db:
    container_name: postgres-demo-db
    build:
      tags:
        - "postgres-demo-db:latest"
      context: .
      dockerfile: Dockerfile_demo_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
