FROM postgres:17.6-trixie
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
  --mount=type=cache,target=/var/lib/apt,sharing=locked <<EOR
apt-get update && apt-get install -y --no-install-recommends \
unzip wget
rm -rf /var/lib/apt/lists/*
EOR

RUN --mount=type=bind,source=demo_db,target=mount,z <<EOR
unzip mount/demo-small.sql.zip
mv demo-small.sql /docker-entrypoint-initdb.d/
# database configuration
sed -i -e 's/^#random_page_cost = 4.0/random_page_cost = 1.1/g' /usr/share/postgresql/postgresql.conf.sample
EOR
